// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: admin.proto

package admin_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BaseClient is the client API for Base service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseClient interface {
	// 添加管理员
	BaseAddAdminer(ctx context.Context, in *AddAdminerReq, opts ...grpc.CallOption) (*AddAdminerResp, error)
	// 更新管理员
	BasePutAdminer(ctx context.Context, in *PutAdminerReq, opts ...grpc.CallOption) (*PutAdminerResp, error)
	// 获取管理员
	BaseGetAdminer(ctx context.Context, in *GetAdminerReq, opts ...grpc.CallOption) (*GetAdminerResp, error)
	// 删除管理员
	BaseDelAdminer(ctx context.Context, in *DelAdminerReq, opts ...grpc.CallOption) (*DelAdminerResp, error)
	// 获取管理员列表
	BaseGetAdminerList(ctx context.Context, in *GetAdminerListReq, opts ...grpc.CallOption) (*GetAdminerListResp, error)
	// 获取管理员枚举列表
	BaseGetAdminerEnums(ctx context.Context, in *GetAdminerEnumsReq, opts ...grpc.CallOption) (*Enums, error)
	// 添加jwt黑名单
	BaseAddJwtBlacklist(ctx context.Context, in *AddJwtBlacklistReq, opts ...grpc.CallOption) (*AddJwtBlacklistResp, error)
	// 更新jwt黑名单
	BasePutJwtBlacklist(ctx context.Context, in *PutJwtBlacklistReq, opts ...grpc.CallOption) (*PutJwtBlacklistResp, error)
	// 获取jwt黑名单
	BaseGetJwtBlacklist(ctx context.Context, in *GetJwtBlacklistReq, opts ...grpc.CallOption) (*GetJwtBlacklistResp, error)
	// 删除jwt黑名单
	BaseDelJwtBlacklist(ctx context.Context, in *DelJwtBlacklistReq, opts ...grpc.CallOption) (*DelJwtBlacklistResp, error)
	// 获取jwt黑名单列表
	BaseGetJwtBlacklistList(ctx context.Context, in *GetJwtBlacklistListReq, opts ...grpc.CallOption) (*GetJwtBlacklistListResp, error)
	// 获取jwt黑名单枚举列表
	BaseGetJwtBlacklistEnums(ctx context.Context, in *GetJwtBlacklistEnumsReq, opts ...grpc.CallOption) (*Enums, error)
}

type baseClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseClient(cc grpc.ClientConnInterface) BaseClient {
	return &baseClient{cc}
}

func (c *baseClient) BaseAddAdminer(ctx context.Context, in *AddAdminerReq, opts ...grpc.CallOption) (*AddAdminerResp, error) {
	out := new(AddAdminerResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseAddAdminer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BasePutAdminer(ctx context.Context, in *PutAdminerReq, opts ...grpc.CallOption) (*PutAdminerResp, error) {
	out := new(PutAdminerResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BasePutAdminer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseGetAdminer(ctx context.Context, in *GetAdminerReq, opts ...grpc.CallOption) (*GetAdminerResp, error) {
	out := new(GetAdminerResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseGetAdminer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseDelAdminer(ctx context.Context, in *DelAdminerReq, opts ...grpc.CallOption) (*DelAdminerResp, error) {
	out := new(DelAdminerResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseDelAdminer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseGetAdminerList(ctx context.Context, in *GetAdminerListReq, opts ...grpc.CallOption) (*GetAdminerListResp, error) {
	out := new(GetAdminerListResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseGetAdminerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseGetAdminerEnums(ctx context.Context, in *GetAdminerEnumsReq, opts ...grpc.CallOption) (*Enums, error) {
	out := new(Enums)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseGetAdminerEnums", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseAddJwtBlacklist(ctx context.Context, in *AddJwtBlacklistReq, opts ...grpc.CallOption) (*AddJwtBlacklistResp, error) {
	out := new(AddJwtBlacklistResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseAddJwtBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BasePutJwtBlacklist(ctx context.Context, in *PutJwtBlacklistReq, opts ...grpc.CallOption) (*PutJwtBlacklistResp, error) {
	out := new(PutJwtBlacklistResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BasePutJwtBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseGetJwtBlacklist(ctx context.Context, in *GetJwtBlacklistReq, opts ...grpc.CallOption) (*GetJwtBlacklistResp, error) {
	out := new(GetJwtBlacklistResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseGetJwtBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseDelJwtBlacklist(ctx context.Context, in *DelJwtBlacklistReq, opts ...grpc.CallOption) (*DelJwtBlacklistResp, error) {
	out := new(DelJwtBlacklistResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseDelJwtBlacklist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseGetJwtBlacklistList(ctx context.Context, in *GetJwtBlacklistListReq, opts ...grpc.CallOption) (*GetJwtBlacklistListResp, error) {
	out := new(GetJwtBlacklistListResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseGetJwtBlacklistList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseClient) BaseGetJwtBlacklistEnums(ctx context.Context, in *GetJwtBlacklistEnumsReq, opts ...grpc.CallOption) (*Enums, error) {
	out := new(Enums)
	err := c.cc.Invoke(ctx, "/admin_proto.Base/BaseGetJwtBlacklistEnums", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServer is the server API for Base service.
// All implementations must embed UnimplementedBaseServer
// for forward compatibility
type BaseServer interface {
	// 添加管理员
	BaseAddAdminer(context.Context, *AddAdminerReq) (*AddAdminerResp, error)
	// 更新管理员
	BasePutAdminer(context.Context, *PutAdminerReq) (*PutAdminerResp, error)
	// 获取管理员
	BaseGetAdminer(context.Context, *GetAdminerReq) (*GetAdminerResp, error)
	// 删除管理员
	BaseDelAdminer(context.Context, *DelAdminerReq) (*DelAdminerResp, error)
	// 获取管理员列表
	BaseGetAdminerList(context.Context, *GetAdminerListReq) (*GetAdminerListResp, error)
	// 获取管理员枚举列表
	BaseGetAdminerEnums(context.Context, *GetAdminerEnumsReq) (*Enums, error)
	// 添加jwt黑名单
	BaseAddJwtBlacklist(context.Context, *AddJwtBlacklistReq) (*AddJwtBlacklistResp, error)
	// 更新jwt黑名单
	BasePutJwtBlacklist(context.Context, *PutJwtBlacklistReq) (*PutJwtBlacklistResp, error)
	// 获取jwt黑名单
	BaseGetJwtBlacklist(context.Context, *GetJwtBlacklistReq) (*GetJwtBlacklistResp, error)
	// 删除jwt黑名单
	BaseDelJwtBlacklist(context.Context, *DelJwtBlacklistReq) (*DelJwtBlacklistResp, error)
	// 获取jwt黑名单列表
	BaseGetJwtBlacklistList(context.Context, *GetJwtBlacklistListReq) (*GetJwtBlacklistListResp, error)
	// 获取jwt黑名单枚举列表
	BaseGetJwtBlacklistEnums(context.Context, *GetJwtBlacklistEnumsReq) (*Enums, error)
	mustEmbedUnimplementedBaseServer()
}

// UnimplementedBaseServer must be embedded to have forward compatible implementations.
type UnimplementedBaseServer struct {
}

func (UnimplementedBaseServer) BaseAddAdminer(context.Context, *AddAdminerReq) (*AddAdminerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseAddAdminer not implemented")
}
func (UnimplementedBaseServer) BasePutAdminer(context.Context, *PutAdminerReq) (*PutAdminerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BasePutAdminer not implemented")
}
func (UnimplementedBaseServer) BaseGetAdminer(context.Context, *GetAdminerReq) (*GetAdminerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseGetAdminer not implemented")
}
func (UnimplementedBaseServer) BaseDelAdminer(context.Context, *DelAdminerReq) (*DelAdminerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseDelAdminer not implemented")
}
func (UnimplementedBaseServer) BaseGetAdminerList(context.Context, *GetAdminerListReq) (*GetAdminerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseGetAdminerList not implemented")
}
func (UnimplementedBaseServer) BaseGetAdminerEnums(context.Context, *GetAdminerEnumsReq) (*Enums, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseGetAdminerEnums not implemented")
}
func (UnimplementedBaseServer) BaseAddJwtBlacklist(context.Context, *AddJwtBlacklistReq) (*AddJwtBlacklistResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseAddJwtBlacklist not implemented")
}
func (UnimplementedBaseServer) BasePutJwtBlacklist(context.Context, *PutJwtBlacklistReq) (*PutJwtBlacklistResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BasePutJwtBlacklist not implemented")
}
func (UnimplementedBaseServer) BaseGetJwtBlacklist(context.Context, *GetJwtBlacklistReq) (*GetJwtBlacklistResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseGetJwtBlacklist not implemented")
}
func (UnimplementedBaseServer) BaseDelJwtBlacklist(context.Context, *DelJwtBlacklistReq) (*DelJwtBlacklistResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseDelJwtBlacklist not implemented")
}
func (UnimplementedBaseServer) BaseGetJwtBlacklistList(context.Context, *GetJwtBlacklistListReq) (*GetJwtBlacklistListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseGetJwtBlacklistList not implemented")
}
func (UnimplementedBaseServer) BaseGetJwtBlacklistEnums(context.Context, *GetJwtBlacklistEnumsReq) (*Enums, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseGetJwtBlacklistEnums not implemented")
}
func (UnimplementedBaseServer) mustEmbedUnimplementedBaseServer() {}

// UnsafeBaseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseServer will
// result in compilation errors.
type UnsafeBaseServer interface {
	mustEmbedUnimplementedBaseServer()
}

func RegisterBaseServer(s grpc.ServiceRegistrar, srv BaseServer) {
	s.RegisterService(&Base_ServiceDesc, srv)
}

func _Base_BaseAddAdminer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdminerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseAddAdminer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseAddAdminer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseAddAdminer(ctx, req.(*AddAdminerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BasePutAdminer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAdminerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BasePutAdminer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BasePutAdminer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BasePutAdminer(ctx, req.(*PutAdminerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseGetAdminer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseGetAdminer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseGetAdminer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseGetAdminer(ctx, req.(*GetAdminerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseDelAdminer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelAdminerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseDelAdminer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseDelAdminer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseDelAdminer(ctx, req.(*DelAdminerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseGetAdminerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseGetAdminerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseGetAdminerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseGetAdminerList(ctx, req.(*GetAdminerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseGetAdminerEnums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminerEnumsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseGetAdminerEnums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseGetAdminerEnums",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseGetAdminerEnums(ctx, req.(*GetAdminerEnumsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseAddJwtBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJwtBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseAddJwtBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseAddJwtBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseAddJwtBlacklist(ctx, req.(*AddJwtBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BasePutJwtBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutJwtBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BasePutJwtBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BasePutJwtBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BasePutJwtBlacklist(ctx, req.(*PutJwtBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseGetJwtBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwtBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseGetJwtBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseGetJwtBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseGetJwtBlacklist(ctx, req.(*GetJwtBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseDelJwtBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelJwtBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseDelJwtBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseDelJwtBlacklist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseDelJwtBlacklist(ctx, req.(*DelJwtBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseGetJwtBlacklistList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwtBlacklistListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseGetJwtBlacklistList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseGetJwtBlacklistList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseGetJwtBlacklistList(ctx, req.(*GetJwtBlacklistListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Base_BaseGetJwtBlacklistEnums_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJwtBlacklistEnumsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServer).BaseGetJwtBlacklistEnums(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Base/BaseGetJwtBlacklistEnums",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServer).BaseGetJwtBlacklistEnums(ctx, req.(*GetJwtBlacklistEnumsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Base_ServiceDesc is the grpc.ServiceDesc for Base service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Base_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_proto.Base",
	HandlerType: (*BaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BaseAddAdminer",
			Handler:    _Base_BaseAddAdminer_Handler,
		},
		{
			MethodName: "BasePutAdminer",
			Handler:    _Base_BasePutAdminer_Handler,
		},
		{
			MethodName: "BaseGetAdminer",
			Handler:    _Base_BaseGetAdminer_Handler,
		},
		{
			MethodName: "BaseDelAdminer",
			Handler:    _Base_BaseDelAdminer_Handler,
		},
		{
			MethodName: "BaseGetAdminerList",
			Handler:    _Base_BaseGetAdminerList_Handler,
		},
		{
			MethodName: "BaseGetAdminerEnums",
			Handler:    _Base_BaseGetAdminerEnums_Handler,
		},
		{
			MethodName: "BaseAddJwtBlacklist",
			Handler:    _Base_BaseAddJwtBlacklist_Handler,
		},
		{
			MethodName: "BasePutJwtBlacklist",
			Handler:    _Base_BasePutJwtBlacklist_Handler,
		},
		{
			MethodName: "BaseGetJwtBlacklist",
			Handler:    _Base_BaseGetJwtBlacklist_Handler,
		},
		{
			MethodName: "BaseDelJwtBlacklist",
			Handler:    _Base_BaseDelJwtBlacklist_Handler,
		},
		{
			MethodName: "BaseGetJwtBlacklistList",
			Handler:    _Base_BaseGetJwtBlacklistList_Handler,
		},
		{
			MethodName: "BaseGetJwtBlacklistEnums",
			Handler:    _Base_BaseGetJwtBlacklistEnums_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	// Preset methods can be deleted. At least one method needs to be defined in a service
	// 预置的方法，可以删除，一个 service 中至少需要定义一个 method
	Test(ctx context.Context, in *NilReq, opts ...grpc.CallOption) (*NilResp, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) Test(ctx context.Context, in *NilReq, opts ...grpc.CallOption) (*NilResp, error) {
	out := new(NilResp)
	err := c.cc.Invoke(ctx, "/admin_proto.Admin/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	// Preset methods can be deleted. At least one method needs to be defined in a service
	// 预置的方法，可以删除，一个 service 中至少需要定义一个 method
	Test(context.Context, *NilReq) (*NilResp, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) Test(context.Context, *NilReq) (*NilResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NilReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin_proto.Admin/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Test(ctx, req.(*NilReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin_proto.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Admin_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
