/**
* author: {{.ProjectAuthor}}
* desc: Generated by {{.ProjectName}}@{{.ProjectVersion}} ({{.ProjectAddr}})
*/

syntax = "proto3";

package {{.Package}};
option go_package="{{.GoPackage}}";

{{.ImportStartMark}}

{{range .Imports}}
import "{{.Filename}}"
{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomImportStartMark}}

{{.CustomImportContent}}

{{.CustomImportEndMark}}

{{.ImportEndMark}}

{{.EnumStartMark}}

{{range .Enums}}
// {{.Comment}}
enum {{.Name}} {
  {{range .Fields}}
  {{.Name}} = {{.Tag}};
  {{end}}
}
{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomEnumStartMark}}

{{.CustomEnumContent}}

{{.CustomEnumEndMark}}

{{.EnumEndMark}}

{{.MessageStartMark}}

//--------- base message start---------

{{range .BaseMessages}}
//{{.Comment}}
message {{.Name}} {
  {{range .Fields}}
  {{.Typ}} {{.Name}} = {{.Tag}}; //{{.Comment}}
  {{end}}
}
{{end}}
//--------- base message end---------

{{range .Messages}}
//{{.Comment}}
message {{.Name}} {
  {{range .Fields}}
  {{.Typ}} {{.Name}} = {{.Tag}}; //{{.Comment}}
  {{end}}
}

{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomMessageStartMark}}

{{.CustomMessageContent}}

{{.CustomMessageEndMark}}

{{.MessageEndMark}}

{{.ServiceStartMark}}

{{if .Multiple}}
service Base{{.ServiceName}} {
  {{range .Services }}
  // {{.Name}} rpc

  {{range .Rpcs}}
  //{{.Comment}}
  rpc {{.Name}}({{.Req}}) returns ({{.Resp}});
  {{end}}

  {{end}}
}

service {{.ServiceName}} {
  // The content in this block will not be updated
  // 此区块内的内容不会被更新
  {{.CustomServiceStartMark}}

  {{.CustomServiceContent}}

  {{.CustomServiceEndMark}}
}
{{else}}
service {{.ServiceName}} {
  {{range .Services }}
  // {{.Name}} rpc

  {{range .Rpcs}}
  //{{.Comment}}
  rpc {{.Name}}({{.Req}}) returns ({{.Resp}});
  {{end}}

  {{end}}

  // The content in this block will not be updated
  // 此区块内的内容不会被更新
  {{.CustomServiceStartMark}}

  {{.CustomServiceContent}}

  {{.CustomServiceEndMark}}
}
{{end}}
{{.ServiceEndMark}}