package conf

var TplContent = `
/**
* author: {{.ProjectAuthor}}
* desc: Generated by {{.ProjectName}}@{{.ProjectVersion}} ({{.ProjectAddr}})
*/

syntax = "proto3";

package {{.Package}};

{{.ImportStartMark}}

{{range .Imports}}
{{printf "import \"%s\";" .Filename -}}
{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomImportStartMark}}

{{.CustomImportContent}}

{{.CustomImportEndMark}}

{{.ImportEndMark}}

option go_package="{{.GoPackage}}";

{{.EnumStartMark}}

{{range .Enums}}
// {{.Comment}}
enum {{.Name}} {
  {{- range .Fields}}
  {{printf "%s = %s;" .Name .Tag -}}
  {{end}}
}
{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomEnumStartMark}}

{{.CustomEnumContent}}

{{.CustomEnumEndMark}}

{{.EnumEndMark}}

{{.MessageStartMark}}

//--------- base message start---------

{{range .BaseMessages}}
//{{.Comment}}
message {{.Name}} {
  {{- range .Fields}}
  {{printf "%s %s = %d; //%s" .Typ .Name .Tag .Comment -}}
  {{end}}
}
{{end}}
//--------- base message end---------

{{range .Messages}}
//{{.Comment}}
message {{.Name}} {
  {{- range .Fields}}
  {{printf "%s %s = %d; //%s" .Typ .Name .Tag .Comment -}}
  {{end}}
}

{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomMessageStartMark}}

{{.CustomMessageContent}}

{{.CustomMessageEndMark}}

{{.MessageEndMark}}

{{.ServiceStartMark}}

{{if .Multiple}}
service Base {
  {{range .Services }}
  // {{.Name}} rpc

  {{range .Rpcs}}
  {{printf "//%s\n rpc %s(%s) returns (%s);" .Comment .Name .Req .Resp -}}
  {{end}}

  {{end}}
}
{{/* 用户自定义service板块start */}}
{{if isEmpty .CustomServiceContent}}
service {{.ServiceName}} {

  // The content in this block will not be updated
  // 此区块内的内容不会被更新
  {{.CustomServiceStartMark}}

  //Preset methods can be deleted. At least one method needs to be defined in a service
  //预置的方法，可以删除，一个 service 中至少需要定义一个 method
  rpc Test(NilReq) returns (NilResp);

  {{.CustomServiceEndMark}}

}
{{else}}
service {{.ServiceName}} {

  // The content in this block will not be updated
  // 此区块内的内容不会被更新
  {{.CustomServiceStartMark}}

  {{.CustomServiceContent}}

  {{.CustomServiceEndMark}}

}
{{end}}
{{/* 用户自定义service板块end */}}
{{else}}
service {{.ServiceName}} {
  {{range .Services }}
  // {{.Name}} rpc

  {{range .Rpcs}}
  {{printf "//%s\n rpc %s(%s) returns (%s);" .Comment .Name .Req .Resp -}}
  {{end}}

  {{end}}

  // The content in this block will not be updated
  // 此区块内的内容不会被更新
  {{.CustomServiceStartMark}}

  {{.CustomServiceContent}}

  {{.CustomServiceEndMark}}

}
{{end}}
{{.ServiceEndMark}}
`
