api:
    dir: ""
    ignoreColumns: []
    ignoreTables: []
    jwt: ""
    middleware: ""
    multiple: false
    prefix: ""
    serviceName: ""
    status: false
    style: genZero
    tables: []
database:
    dsn: ""
    ignoreColumns: []
    ignoreTables: []
    src: ""
    tables: []
logic:
    api:
        dir: ""
        ignoreTables: []
        status: false
        style: genZero
        tables: []
        useRpc: false
    rpc:
        dir: ""
        ignoreTables: []
        multiple: false
        status: false
        style: genZero
        tables: []
    status: false
model:
    dir: ""
    ignoreColumns: []
    ignoreTables: []
    status: false
    tables: []
proto:
    dir: ""
    goPackage: ""
    ignoreColumns: []
    ignoreTables: []
    multiple: false
    package: ""
    serviceName: ""
    status: false
    style: genZero
    tables: []
