syntax = "v1"

info (
	title: {{.ServiceName}}
	author: {{.ProjectAuthor}}
  desc: Generated by {{.ProjectName}}@{{.ProjectVersion}} ({{.ProjectAddr}})
)

{{.ImportStartMark}}

{{if .CurrentIsCoreFile}}
{{range .Imports}}
import "{{.Filename}}"
{{end}}
{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomImportStartMark}}

{{.CustomImportContent}}

{{.CustomImportEndMark}}

{{.ImportEndMark}}

{{.StructStartMark}}

{{if .CurrentIsCoreFile}}
//--------- base struct start---------

{{range .BaseStructs}}
//{{.Comment}}
type {{.Name}} {
  {{range .Fields}}
  {{.Name}} {{.Typ}} ^{{.TagType}}:{{.TagName}},{{.TagOpt}}^; //{{.Comment}}
  {{end}}
}

{{end}}

//--------- base struct end---------
{{end}}

{{if NeedRenderStruct .Multiple .CurrentIsCoreFile}}

{{range .Structs}}
//{{.Comment}}
type {{.Name}} {
  {{range .Fields}}
  {{.Name}} {{.Typ}} ^{{.TagType}}:{{.TagName}},{{.TagOpt}}^; //{{.Comment}}
  {{end}}
}
{{end}}

{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomStructStartMark}}

{{.CustomStructContent}}

{{.CustomStructEndMark}}

{{.StructEndMark}}

{{if NeedRenderStruct .Multiple .CurrentIsCoreFile}}

{{range .Services}}
@server(
  jwt: {{.Server.Jwt}}
  group: {{.Server.Group}}
  middleware: {{.Server.Middleware}}
  prefix: {{.Server.Prefix}}
)
service {{$.ServiceName}} {
  {{range .Apis}}
  @doc "{{.Comment}}"
	@handler {{.Handler}}
	{{.Method}} {{.Path}}({{.Req}}) returns({{.Resp}})

  {{end}}
}
{{end}}

{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomServiceStartMark}}

{{.CustomServiceContent}}

{{.CustomServiceEndMark}}