package conf

var TplContent = `
syntax = "v1"

info (
	title: {{.ServiceName}}-api
	author: {{.ProjectAuthor}}
  desc: Generated by {{.ProjectName}}@{{.ProjectVersion}} ({{.ProjectAddr}})
)

{{.ImportStartMark}}

{{if .CurrentIsCoreFile}}
{{range .Imports}}
{{printf "import \"%s\";" .Filename -}}
{{end}}
{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomImportStartMark}}

{{.CustomImportContent}}

{{.CustomImportEndMark}}

{{.ImportEndMark}}

{{.StructStartMark}}

{{if .CurrentIsCoreFile}}
//--------- base struct start---------

{{range .BaseStructs}}
//{{.Comment}}
type {{.Name}} {
  {{- range .Fields}}
  {{printf "%s %s %s //%s" .Name .Typ .TagString .Comment -}}
  {{end}}
}

{{end}}

//--------- base struct end---------
{{end}}

{{if NeedRenderStruct .Multiple .CurrentIsCoreFile}}

{{range .Structs}}
//{{.Comment}}
type {{.Name}} {
  {{- range .Fields}}
  {{printf "%s %s %s //%s" .Name .Typ .TagString .Comment -}}
  {{end}}
}
{{end}}

{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomStructStartMark}}

{{.CustomStructContent}}

{{.CustomStructEndMark}}

{{.StructEndMark}}

{{if NeedRenderStruct .Multiple .CurrentIsCoreFile}}

{{range .Services}}
{{.Server}}
service {{$.ServiceName}} {
  {{range .Apis}}
  @doc "{{.Comment}}"
	@handler {{.Handler}}
	{{.Method}} {{.Path}}({{.Req}}) returns({{.Resp}})

  {{end}}
}
{{end}}

{{end}}

// The content in this block will not be updated
// 此区块内的内容不会被更新
{{.CustomServiceStartMark}}

{{.CustomServiceContent}}

{{.CustomServiceEndMark}}
`
