// Code generated by {{.ProjectName}}. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
)

type {{.InterfaceName}} interface {
	{{range .Funcs}}
	{{ .FullName | printf "%s"  }}
	{{end}}
}

{{range .Funcs}}
{{.}}
{{end}}