// Code generated by {{.ProjectName}}. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"github.com/Masterminds/squirrel"
)

var {{ToCamel .TableName}}TableName = "{{.TableName}}"

type {{.InterfaceName}} interface {
	{{- range $.FuncNameList}}
	{{. -}}
	{{end}}
}

{{range .Funcs}}
{{.}}
{{end}}