api:
    dir: ""
    ignoreColumns: []
    ignoreTables:
        - jwt_blacklist
    jwt: ""
    middleware: ""
    multiple: false
    prefix: ""
    serviceName: admin-api
    status: false
    style: genZero
    tables: []
database:
    dsn: ""
    ignoreColumns: []
    ignoreTables: []
    src: ../sql/admin.sql
    tables: []
logic:
    api:
        dir: api/internal/logic
        ignoreTables: []
        status: true
        style: genZero
        tables: []
        useRpc: true
    rpc:
        dir: rpc/internal/logic
        ignoreTables: []
        multiple: true
        status: true
        style: genZero
        tables: []
    status: true
model:
    dir: model
    ignoreColumns: []
    ignoreTables: []
    status: true
    tables: []
proto:
    dir: ""
    goPackage: ""
    ignoreColumns: []
    ignoreTables: []
    multiple: false
    package: ""
    serviceName: admin
    status: false
    style: genZero
    tables: []
