database:
    dsn: ""
    src: "../sql/admin.sql"
    tables: []
    ignoreTables: []
    ignoreColumns: []
api:
    status: true
    style: ""
    jwt: ""
    middleware: ""
    prefix: ""
    multiple: false
    dir: ""
    serviceName: "admin-api"
    tables: []
    ignoreTables: ["jwt_blacklist"]
    ignoreColumns: []
proto:
    status: true
    package: ""
    goPackage: ""
    multiple: true
    dir: ""
    serviceName: "admin"
    tables: []
    ignoreTables: []
    ignoreColumns: []
model:
    status: true
    dir: "model"
    tables: []
    ignoreTables: []
    ignoreColumns: []
logic:
    status: false
    api:
        status: false
        useRpc: false
        dir: ""
        tables: []
        ignoreTables: []
    rpc:
        status: false
        multiple: false
        dir: ""
        tables: []
        ignoreTables: []
