// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package client

import (
	"context"

	"github.com/licat233/genzero/examples/all/rpc/admin_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAdminerReq           = admin_pb.AddAdminerReq
	AddAdminerResp          = admin_pb.AddAdminerResp
	AddJwtBlacklistReq      = admin_pb.AddJwtBlacklistReq
	AddJwtBlacklistResp     = admin_pb.AddJwtBlacklistResp
	Adminer                 = admin_pb.Adminer
	ByIdReq                 = admin_pb.ByIdReq
	DelAdminerReq           = admin_pb.DelAdminerReq
	DelAdminerResp          = admin_pb.DelAdminerResp
	DelJwtBlacklistReq      = admin_pb.DelJwtBlacklistReq
	DelJwtBlacklistResp     = admin_pb.DelJwtBlacklistResp
	Enum                    = admin_pb.Enum
	Enums                   = admin_pb.Enums
	GetAdminerEnumsReq      = admin_pb.GetAdminerEnumsReq
	GetAdminerListReq       = admin_pb.GetAdminerListReq
	GetAdminerListResp      = admin_pb.GetAdminerListResp
	GetAdminerReq           = admin_pb.GetAdminerReq
	GetAdminerResp          = admin_pb.GetAdminerResp
	GetJwtBlacklistEnumsReq = admin_pb.GetJwtBlacklistEnumsReq
	GetJwtBlacklistListReq  = admin_pb.GetJwtBlacklistListReq
	GetJwtBlacklistListResp = admin_pb.GetJwtBlacklistListResp
	GetJwtBlacklistReq      = admin_pb.GetJwtBlacklistReq
	GetJwtBlacklistResp     = admin_pb.GetJwtBlacklistResp
	JwtBlacklist            = admin_pb.JwtBlacklist
	ListReq                 = admin_pb.ListReq
	NilReq                  = admin_pb.NilReq
	NilResp                 = admin_pb.NilResp
	Option                  = admin_pb.Option
	Options                 = admin_pb.Options
	PutAdminerReq           = admin_pb.PutAdminerReq
	PutAdminerResp          = admin_pb.PutAdminerResp
	PutJwtBlacklistReq      = admin_pb.PutJwtBlacklistReq
	PutJwtBlacklistResp     = admin_pb.PutJwtBlacklistResp
	StatusResp              = admin_pb.StatusResp
	TreeOption              = admin_pb.TreeOption
	TreeOptions             = admin_pb.TreeOptions

	Base interface {
		// 添加管理员
		BaseAddAdminer(ctx context.Context, in *AddAdminerReq, opts ...grpc.CallOption) (*AddAdminerResp, error)
		// 更新管理员
		BasePutAdminer(ctx context.Context, in *PutAdminerReq, opts ...grpc.CallOption) (*PutAdminerResp, error)
		// 获取管理员
		BaseGetAdminer(ctx context.Context, in *GetAdminerReq, opts ...grpc.CallOption) (*GetAdminerResp, error)
		// 删除管理员
		BaseDelAdminer(ctx context.Context, in *DelAdminerReq, opts ...grpc.CallOption) (*DelAdminerResp, error)
		// 获取管理员列表
		BaseGetAdminerList(ctx context.Context, in *GetAdminerListReq, opts ...grpc.CallOption) (*GetAdminerListResp, error)
		// 获取管理员枚举列表
		BaseGetAdminerEnums(ctx context.Context, in *GetAdminerEnumsReq, opts ...grpc.CallOption) (*Enums, error)
		// 添加jwt黑名单
		BaseAddJwtBlacklist(ctx context.Context, in *AddJwtBlacklistReq, opts ...grpc.CallOption) (*AddJwtBlacklistResp, error)
		// 更新jwt黑名单
		BasePutJwtBlacklist(ctx context.Context, in *PutJwtBlacklistReq, opts ...grpc.CallOption) (*PutJwtBlacklistResp, error)
		// 获取jwt黑名单
		BaseGetJwtBlacklist(ctx context.Context, in *GetJwtBlacklistReq, opts ...grpc.CallOption) (*GetJwtBlacklistResp, error)
		// 删除jwt黑名单
		BaseDelJwtBlacklist(ctx context.Context, in *DelJwtBlacklistReq, opts ...grpc.CallOption) (*DelJwtBlacklistResp, error)
		// 获取jwt黑名单列表
		BaseGetJwtBlacklistList(ctx context.Context, in *GetJwtBlacklistListReq, opts ...grpc.CallOption) (*GetJwtBlacklistListResp, error)
		// 获取jwt黑名单枚举列表
		BaseGetJwtBlacklistEnums(ctx context.Context, in *GetJwtBlacklistEnumsReq, opts ...grpc.CallOption) (*Enums, error)
	}

	defaultBase struct {
		cli zrpc.Client
	}
)

func NewBase(cli zrpc.Client) Base {
	return &defaultBase{
		cli: cli,
	}
}

// 添加管理员
func (m *defaultBase) BaseAddAdminer(ctx context.Context, in *AddAdminerReq, opts ...grpc.CallOption) (*AddAdminerResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseAddAdminer(ctx, in, opts...)
}

// 更新管理员
func (m *defaultBase) BasePutAdminer(ctx context.Context, in *PutAdminerReq, opts ...grpc.CallOption) (*PutAdminerResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BasePutAdminer(ctx, in, opts...)
}

// 获取管理员
func (m *defaultBase) BaseGetAdminer(ctx context.Context, in *GetAdminerReq, opts ...grpc.CallOption) (*GetAdminerResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseGetAdminer(ctx, in, opts...)
}

// 删除管理员
func (m *defaultBase) BaseDelAdminer(ctx context.Context, in *DelAdminerReq, opts ...grpc.CallOption) (*DelAdminerResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseDelAdminer(ctx, in, opts...)
}

// 获取管理员列表
func (m *defaultBase) BaseGetAdminerList(ctx context.Context, in *GetAdminerListReq, opts ...grpc.CallOption) (*GetAdminerListResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseGetAdminerList(ctx, in, opts...)
}

// 获取管理员枚举列表
func (m *defaultBase) BaseGetAdminerEnums(ctx context.Context, in *GetAdminerEnumsReq, opts ...grpc.CallOption) (*Enums, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseGetAdminerEnums(ctx, in, opts...)
}

// 添加jwt黑名单
func (m *defaultBase) BaseAddJwtBlacklist(ctx context.Context, in *AddJwtBlacklistReq, opts ...grpc.CallOption) (*AddJwtBlacklistResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseAddJwtBlacklist(ctx, in, opts...)
}

// 更新jwt黑名单
func (m *defaultBase) BasePutJwtBlacklist(ctx context.Context, in *PutJwtBlacklistReq, opts ...grpc.CallOption) (*PutJwtBlacklistResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BasePutJwtBlacklist(ctx, in, opts...)
}

// 获取jwt黑名单
func (m *defaultBase) BaseGetJwtBlacklist(ctx context.Context, in *GetJwtBlacklistReq, opts ...grpc.CallOption) (*GetJwtBlacklistResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseGetJwtBlacklist(ctx, in, opts...)
}

// 删除jwt黑名单
func (m *defaultBase) BaseDelJwtBlacklist(ctx context.Context, in *DelJwtBlacklistReq, opts ...grpc.CallOption) (*DelJwtBlacklistResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseDelJwtBlacklist(ctx, in, opts...)
}

// 获取jwt黑名单列表
func (m *defaultBase) BaseGetJwtBlacklistList(ctx context.Context, in *GetJwtBlacklistListReq, opts ...grpc.CallOption) (*GetJwtBlacklistListResp, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseGetJwtBlacklistList(ctx, in, opts...)
}

// 获取jwt黑名单枚举列表
func (m *defaultBase) BaseGetJwtBlacklistEnums(ctx context.Context, in *GetJwtBlacklistEnumsReq, opts ...grpc.CallOption) (*Enums, error) {
	client := admin_pb.NewBaseClient(m.cli.Conn())
	return client.BaseGetJwtBlacklistEnums(ctx, in, opts...)
}
