// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminer "github.com/licat233/genzero/examples/all/api/internal/handler/adminer"
	"github.com/licat233/genzero/examples/all/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: adminer.AddAdminerHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: adminer.PutAdminerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: adminer.GetAdminerHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: adminer.DelAdminerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: adminer.GetAdminerListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/enums",
				Handler: adminer.GetAdminerEnumsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/adminer"),
	)
}
