// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package admin

import (
	"context"

	"github.com/licat233/genzero/examples/all/rpc/admin_pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAdminerReq           = admin_pb.AddAdminerReq
	AddAdminerResp          = admin_pb.AddAdminerResp
	AddJwtBlacklistReq      = admin_pb.AddJwtBlacklistReq
	AddJwtBlacklistResp     = admin_pb.AddJwtBlacklistResp
	Adminer                 = admin_pb.Adminer
	ByIdReq                 = admin_pb.ByIdReq
	DelAdminerReq           = admin_pb.DelAdminerReq
	DelAdminerResp          = admin_pb.DelAdminerResp
	DelJwtBlacklistReq      = admin_pb.DelJwtBlacklistReq
	DelJwtBlacklistResp     = admin_pb.DelJwtBlacklistResp
	Enum                    = admin_pb.Enum
	Enums                   = admin_pb.Enums
	GetAdminerEnumsReq      = admin_pb.GetAdminerEnumsReq
	GetAdminerListReq       = admin_pb.GetAdminerListReq
	GetAdminerListResp      = admin_pb.GetAdminerListResp
	GetAdminerReq           = admin_pb.GetAdminerReq
	GetAdminerResp          = admin_pb.GetAdminerResp
	GetJwtBlacklistEnumsReq = admin_pb.GetJwtBlacklistEnumsReq
	GetJwtBlacklistListReq  = admin_pb.GetJwtBlacklistListReq
	GetJwtBlacklistListResp = admin_pb.GetJwtBlacklistListResp
	GetJwtBlacklistReq      = admin_pb.GetJwtBlacklistReq
	GetJwtBlacklistResp     = admin_pb.GetJwtBlacklistResp
	JwtBlacklist            = admin_pb.JwtBlacklist
	ListReq                 = admin_pb.ListReq
	NilReq                  = admin_pb.NilReq
	NilResp                 = admin_pb.NilResp
	Option                  = admin_pb.Option
	Options                 = admin_pb.Options
	PutAdminerReq           = admin_pb.PutAdminerReq
	PutAdminerResp          = admin_pb.PutAdminerResp
	PutJwtBlacklistReq      = admin_pb.PutJwtBlacklistReq
	PutJwtBlacklistResp     = admin_pb.PutJwtBlacklistResp
	StatusResp              = admin_pb.StatusResp
	TreeOption              = admin_pb.TreeOption
	TreeOptions             = admin_pb.TreeOptions

	Admin interface {
		// Preset methods can be deleted. At least one method needs to be defined in a service
		Test(ctx context.Context, in *NilReq, opts ...grpc.CallOption) (*NilResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

// Preset methods can be deleted. At least one method needs to be defined in a service
func (m *defaultAdmin) Test(ctx context.Context, in *NilReq, opts ...grpc.CallOption) (*NilResp, error) {
	client := admin_pb.NewAdminClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
