// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"github.com/licat233/genzero/examples/all/rpc/admin_pb"
	"github.com/licat233/genzero/examples/all/rpc/internal/logic/admin"
	"github.com/licat233/genzero/examples/all/rpc/internal/svc"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin_pb.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

// Preset methods can be deleted. At least one method needs to be defined in a service
func (s *AdminServer) Test(ctx context.Context, in *admin_pb.NilReq) (*admin_pb.NilResp, error) {
	l := adminlogic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}
